# Generated by Django 4.2.11 on 2024-04-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_category_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Python", "Python"),
                    ("Java", "Java"),
                    ("C++", "C++"),
                    ("JavaScript", "JavaScript"),
                    ("Ruby", "Ruby"),
                ],
                default="Python",
                max_length=10,
            ),
        ),
    ]
